
desc "Lint and test the library"
lane :test do
  # Using the package manager supplied SwiftLint, no Brew needed
  sh "cd ..; swift run swiftlint; cd -;"
  pod_lib_lint
  spm(
    command: "generate-xcodeproj"
  )
  run_tests
end
