name: Test

on:
  - pull_request

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v6
    - name: Lint
      run: |
        swiftlint --strict
    - name: Test
      run: |
        xcodebuild -scheme FuntastyKit -destination 'platform=iOS Simulator,name=iPhone 16' -sdk iphonesimulator test
